In [1]:
#Numpy-Numerical Python
#mathematical or Statistical calcualtion
#pip install numpy

In [2]:
#Load the libraries
import numpy as np

In [3]:
x=[13,45]
y=[123,45]
x+y

[13, 45, 123, 45]

In [4]:
a=np.array([10,20])
b=np.array([30,40])

In [5]:
type(a)

numpy.ndarray

In [6]:
type(x)

list

In [7]:
a+b

array([40, 60])

In [8]:
a*b

array([300, 800])

In [9]:
np.add(a,b)

array([40, 60])

In [10]:
a.ndim#Know the dimension

1

In [17]:
c=np.array([[12,345],[123,45]])

In [12]:
c.ndim

2

In [13]:
a

array([10, 20])

In [15]:
a.shape

(2,)

In [18]:
c.shape

(2, 2)

In [19]:
c

array([[ 12, 345],
       [123,  45]])

In [21]:
a.sum()

30

In [22]:
a

array([10, 20])

In [24]:
a.max()

20

In [25]:
a.min()

10

In [26]:
a.mean()

15.0

In [28]:
a.dot(b)

1100

In [29]:
a*b

array([300, 800])

In [30]:
c=np.array([[12,34,55],[256,100,400],[56,763,78],[90,80,60]])

In [31]:
c

array([[ 12,  34,  55],
       [256, 100, 400],
       [ 56, 763,  78],
       [ 90,  80,  60]])

In [32]:
#[r,c]
np.shape(c)

(4, 3)

In [33]:
c

array([[ 12,  34,  55],
       [256, 100, 400],
       [ 56, 763,  78],
       [ 90,  80,  60]])

In [34]:
c[1][1]

100

In [37]:
#[r,:]
c[0:2,:]

array([[ 12,  34,  55],
       [256, 100, 400]])

In [38]:
#[:,c]
c[:,2]

array([ 55, 400,  78,  60])

In [39]:
c

array([[ 12,  34,  55],
       [256, 100, 400],
       [ 56, 763,  78],
       [ 90,  80,  60]])

In [40]:
c[3][2]=600

In [41]:
c

array([[ 12,  34,  55],
       [256, 100, 400],
       [ 56, 763,  78],
       [ 90,  80, 600]])

In [42]:
c[1,:]=[20,10,40]

In [43]:
c

array([[ 12,  34,  55],
       [ 20,  10,  40],
       [ 56, 763,  78],
       [ 90,  80, 600]])

In [44]:
c[:,1]=[30,30,30,30]

In [45]:
c

array([[ 12,  30,  55],
       [ 20,  30,  40],
       [ 56,  30,  78],
       [ 90,  30, 600]])

In [46]:
np.shape(c)

(4, 3)

In [47]:
np.reshape(c,(3,4))

array([[ 12,  30,  55,  20],
       [ 30,  40,  56,  30],
       [ 78,  90,  30, 600]])

In [48]:
np.mean(c)

89.25

In [49]:
np.median(c)

35.0

In [50]:
np.std(c)

155.5908764463178

In [51]:
np.var(c)

24208.520833333332

In [52]:
np.max(c)

600

In [58]:
c

array([[ 12,  30,  55],
       [ 20,  30,  40],
       [ 56,  30,  78],
       [900,  30, 600]])

In [57]:
np.max(c,axis=1)#Rows data

array([ 55,  40,  78, 900])

In [55]:
c[3][0]=900

In [56]:
c

array([[ 12,  30,  55],
       [ 20,  30,  40],
       [ 56,  30,  78],
       [900,  30, 600]])

In [59]:
np.min(c,axis=1)#Row

array([12, 20, 30, 30])

In [60]:
np.max(c,axis=0)#Columns

array([900,  30, 600])

In [62]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
c

array([[ 12,  30,  55],
       [ 20,  30,  40],
       [ 56,  30,  78],
       [900,  30, 600]])

In [66]:
c.shape

(4, 3)

In [67]:
np.zeros_like(c)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [68]:
np.ones_like(c)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [69]:
c

array([[ 12,  30,  55],
       [ 20,  30,  40],
       [ 56,  30,  78],
       [900,  30, 600]])

In [70]:
np.diag(c)

array([12, 30, 78])

In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [74]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.diagonal([[10,20,30],[23,45,67],[1134,45436,67]])

array([10, 45, 67])

In [79]:
np.empty(3)

array([1., 1., 1.])

In [80]:
np.empty_like(c)

array([[         0, 1072693248,          0],
       [1072693248,          0, 1072693248],
       [         0, 1072693248,          0],
       [1072693248,          0, 1072693248]])

In [82]:
np.full((2,3),45)

array([[45, 45, 45],
       [45, 45, 45]])

In [83]:
np.full_like(c,100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [84]:
np.log10(c)

array([[1.07918125, 1.47712125, 1.74036269],
       [1.30103   , 1.47712125, 1.60205999],
       [1.74818803, 1.47712125, 1.8920946 ],
       [2.95424251, 1.47712125, 2.77815125]])

In [85]:
np.sin(c)

array([[-0.53657292, -0.98803162, -0.99975517],
       [ 0.91294525, -0.98803162,  0.74511316],
       [-0.521551  , -0.98803162,  0.51397846],
       [ 0.99780327, -0.98803162,  0.04418245]])

In [86]:
np.cos(c)

array([[ 0.84385396,  0.15425145,  0.02212676],
       [ 0.40808206,  0.15425145, -0.66693806],
       [ 0.85322011,  0.15425145, -0.85780309],
       [ 0.0662467 ,  0.15425145, -0.99902348]])

In [87]:
c

array([[ 12,  30,  55],
       [ 20,  30,  40],
       [ 56,  30,  78],
       [900,  30, 600]])

In [88]:
c.astype('float')

array([[ 12.,  30.,  55.],
       [ 20.,  30.,  40.],
       [ 56.,  30.,  78.],
       [900.,  30., 600.]])